### ISSUE TITLE
Logger always outputs to console

### ISSUE THREAD

**Issue by ogroppo** [seanpmaxwell/jet-logger#1]
Hi, I'm using the package like this

.env `JET_LOGGER_MODE=OFF`

```
import Logger from "jet-logger";

const logger = new Logger();

logger.err("string")
```
I would expect to see no output in console, but the error is printed.

**Comment by seanpmaxwell** [comment]
I just tested it and it's working for me. Are you sure you're loading the environment variables before initializing logger?

**Comment by ogroppo** [comment]
Mhhh, odd... yes I just did this in the code:
<img width="528" alt="Screenshot 2021-03-01 at 20 17 06" src="https://user-images.githubusercontent.com/4820803/109553679-39b44f80-7acb-11eb-8e84-0fef821cc9e8.png">

And the result in terminal
<img width="292" alt="Screenshot 2021-03-01 at 20 18 28" src="https://user-images.githubusercontent.com/4820803/109553749-4e90e300-7acb-11eb-9be4-cc3b26faaf28.png">

Hope this is not affected by NODE_ENV? (being in `test` here)

**Comment by ogroppo** [comment]
Ah, just realised this project is yours https://github.com/seanpmaxwell/express-generator-typescript 👏 👏 👏 

It seems that when running `npm test` the env file in `pre-start` is picked up after `src/shared/Logger.ts` is initialised , so indeed `process.env.JET_LOGGER_MODE` is undefined at that point.

**Comment by seanpmaxwell** [comment]
Thanks. Issue was with express-generator-typescript. Please see version 1.7.3. Please give jet-logger and express-generator-typescript a gitstar if you can.
