### ISSUE TITLE
URGENT: Downgrade colors package or use something else

### ISSUE THREAD

**Issue by ukstv** [seanpmaxwell/jet-logger#2]
Recently, the maintainer of the colors npm package has decided to go rogue. Read [here](https://github.com/Marak/colors.js/commit/074a0f8ed0c31c35d13d28632bd8a049ff136fb6) and [here](https://www.reddit.com/r/javascript/comments/rz56qu/marak_adds_infinite_loop_to_colorsjs/).

It seems, it is good to downgrade to colors 1.3 or use something else, like [kleur](https://github.com/lukeed/kleur#readme)

**Comment by seanpmaxwell** [comment]
Omg, seems like the guy turned out to be a total psycho.

**Comment by seanpmaxwell** [comment]
done, switched colors to version 1.3. Also switched from class-based to structure/function based architecture since that seems to be the direction of javascript these days.
